version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: make ci-install
      - run: make ci-lint
  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: make ci-test
      - codecov/upload:
          file: coverage/coverage.xml

workflows:
  ci-test:
    jobs:
      - lint
      - test
