version: 2.1

mermaider_ci_image: &mermaider_ci_image
  - image: cimg/python:stable

jobs:
  lint:
    docker:
      - image: cimg/python:stable
    steps:
      - run: make ci-lint
  test:
    docker:
      - image: cimg/python:stable
    steps:
      - run: make ci-lint

workflows:
  ci-test:
    jobs:
      - lint
      - test
