version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: make ci-install
      - run: make ci-lint
  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: make ci-install
      - run: make ci-lint

workflows:
  ci-test:
    jobs:
      - lint
      - test
